version: "3.8"

services:
  frontend:
    command: npm run start
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src