version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: docker-example-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - docker-example-network
  api:
    build:
      context: ./api
      args:
        - workdir=/usr/src/app
    container_name: docker-example-api
    command: java -jar /usr/src/app/api.jar
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=docker-example.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - docker-example-network
  auth:
    build:
      context: ./auth
      args:
        - workdir=/usr/src/app
    container_name: docker-example-auth
    command: java -jar /usr/src/app/auth.jar
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=docker-example.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - docker-example-network
  api_db:
    image: mongo:4.4.2
    container_name: docker-example-api-db
    volumes:
      - mongodb_api:/data/db
    networks:
      - docker-example-network
  auth_db:
    image: mongo:4.4.2
    container_name: docker-example-auth-db
    volumes:
      - mongodb_auth:/data/db
    networks:
      - docker-example-network
  nginx:
    image: nginx:stable-alpine
    container_name: docker-example-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - docker-example-network

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  docker-example-network:
    driver: bridge