version: "3.8"
services:
  api:
    build:
      context: ./api
      args:
        - workdir=/usr/src/app
    command: java -jar /usr/src/app/target/api-1.0.0.jar
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=docker-example.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:4.4.2
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api: