spring:
  application:
    name: api
  data:
    mongodb:
      uri: ${api.db-url}
  devtools:
    remote:
      secret: my_secret

api:
  server:
    port: ${PORT}
    host: ${HOST}
  db-url: ${MONGO_URL}
  auth-api-url: ${AUTH_API_URL}

server:
  port: ${api.server.port}
